# Generated by Django 4.2.7 on 2023-11-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_dealer_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
