# Generated by Django 4.2.7 on 2023-11-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_dealer_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dealer',
        ),
    ]
